apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: miner-web-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: ino-miner-basic-web
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30 # The web pod Requests 0.2 CPU, so when it hits 0.06 CPU, add a replica!