apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ino-miner-basic-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ino-miner-basic-web
    spec:
      containers:
      - name: ino-miner-basic-web
        image: inobitscr.azurecr.io/liver_web:4  
        resources:
          limits:
            cpu: "0.3" # Not allowed to use 1/3 of the Node's CPU
          requests:
            cpu: "0.2" # Only start this Pod on a Node where 1/5 of the CPU is available consider other Pods' requests 
        env:
          - name: ConnectionStrings__MiningDBContext
            valueFrom:
              secretKeyRef:
                name: connectionstringmining 
                key: connectionstringmining  
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name : inobitscr
---
apiVersion: v1
kind: Service
metadata:
  name: ino-miner-basic-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: ino-miner-basic-web
